# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minke', '0003_auto_20190315_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='minke.Host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThisAndThat',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('minke.session',),
        ),
        migrations.AddField(
            model_name='anysystem',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Server'),
        ),
    ]
