# Generated by Django 2.1.7 on 2019-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('session_cls', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
