# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'permissions': (('run_host_minke_sessions', 'Can run minke-sessions'),)},
        ),
    ]
