# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-12 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0003_auto_20181028_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='locked',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
