# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0003_auto_20181028_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basesession',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('warning', 'warning'), ('error', 'error')], max_length=128),
        ),
    ]
