# Generated by Django 2.1.7 on 2019-06-14 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fabric2.runners


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0003_auto_20190326_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('exited', models.SmallIntegerField()),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('shell', models.CharField(max_length=128)),
                ('encoding', models.CharField(max_length=128)),
                ('pty', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('session', 'created_time'),
                'verbose_name_plural': 'Command-Results',
                'verbose_name': 'Command-Result',
            },
            bases=(fabric2.runners.Result, models.Model),
        ),
        migrations.AlterModelOptions(
            name='basemessage',
            options={'ordering': ('session', 'created_time'), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['name'], 'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'ordering': ['name'], 'verbose_name': 'Hostgroup', 'verbose_name_plural': 'Hostgroups'},
        ),
        migrations.AlterModelOptions(
            name='minkesession',
            options={'ordering': ('minkeobj_type', 'minkeobj_id', '-created_time'), 'verbose_name': 'Minke-Session', 'verbose_name_plural': 'Minke-Sessions'},
        ),
        migrations.AddField(
            model_name='basemessage',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minkesession',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minkesession',
            name='task_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='minkesession',
            name='proc_status',
            field=models.CharField(choices=[('initialized', 'initialized'), ('running', 'running'), ('completed', 'completed'), ('stopping', 'stopping'), ('stopped', 'stopped'), ('canceled', 'canceled'), ('failed', 'failed')], max_length=128),
        ),
        migrations.AddField(
            model_name='commandresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='minke.MinkeSession'),
        ),
    ]
