# Generated by Django 2.1.7 on 2019-06-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0004_auto_20190530_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('return_code', models.SmallIntegerField()),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('shell', models.CharField(max_length=128)),
                ('encoding', models.CharField(max_length=128)),
                ('pty', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='minke.MinkeSession')),
            ],
        ),
    ]
