# Generated by Django 2.2.8 on 2020-01-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0005_auto_20190810_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='name',
            field=models.CharField(help_text='Unique group-name.', max_length=128, unique=True, verbose_name='Group-Name'),
        ),
    ]
