# Generated by Django 2.2.24 on 2023-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0006_auto_20200108_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='group',
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Hostgroups this host belongs to.', related_name='hosts', to='minke.HostGroup', verbose_name='Hostgroup'),
        ),
    ]
