# Generated by Django 2.2.28 on 2023-04-05 21:53

from django.db import migrations, models
import minke.utils


class Migration(migrations.Migration):

    dependencies = [
        ('minke', '0007_auto_20230404_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='config',
            field=models.TextField(blank=True, default='', help_text='A yaml formatted fabric/invoke configuration.', validators=[minke.utils.valid_yaml_configuration], verbose_name='Fabric and invoke configuration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='config',
            field=models.TextField(blank=True, default='', help_text='A yaml formatted fabric/invoke configuration.', validators=[minke.utils.valid_yaml_configuration], verbose_name='Fabric and invoke configuration'),
            preserve_default=False,
        ),
    ]
